# Generated by Django 5.0.7 on 2024-07-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('capa', models.CharField(max_length=45)),
                ('titulo', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musica', models.CharField(max_length=45)),
                ('artista_musica', models.CharField(max_length=45)),
                ('album_musica', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musica', models.CharField(max_length=50)),
                ('nome_artista', models.CharField(max_length=30)),
                ('album_musica', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.midia')),
            ],
        ),
        migrations.CreateModel(
            name='Trilhas_das_musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musicas')),
                ('trilhas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trilhas')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('pontuacao', models.CharField(max_length=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]




















