# Generated by Django 4.2.6 on 2024-09-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apelido',
            new_name='confirmar_senha',
        ),
    ]
