# Generated by Django 4.2.6 on 2024-09-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_apelido_usuario_confirmar_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='Usuario',
        ),
    ]
