# Generated by Django 4.2.6 on 2024-09-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_email_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_senha',
        ),
    ]
