# Generated by Django 4.2.6 on 2024-09-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usuario_confirmar_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
