# Generated by Django 4.0.3 on 2024-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_usuario_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='ano',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlists',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlists',
            name='imagem',
            field=models.ImageField(blank=True, default='icon user.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='playlists',
            name='nome_filme',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
