# Generated by Django 5.1.1 on 2024-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playlists_ano_playlists_descricao_playlists_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='imagem',
            field=models.ImageField(blank=True, default='carros.png', upload_to='images/'),
        ),
    ]
